# This is a basic workflow to help you get started with Actions

name: CI


on: [push,pull_request]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out source code
      uses: actions/checkout@v2

    - name: Build
      run: go build .
      
  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out source code
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./action
