# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  test:
    name: deploy to staging
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out source code
      uses: actions/checkout@master

    - name: Build
      run: go build .

    - name: Test
      run: go test -v ./action
